query GetEmpleadoById($id: Int!) {
    getEmpleadoById(id: $id) {
        success
        data {
            IdEmpleado
            Empleado
            Cargo {
                IdCargo
                Cargo
            }
            Division {
                IdDivision
                Division
            }
        }
        error
    }
}