query GetAllComprobarExpresiones {
    getAllComprobarExpresiones {
        success
        data {
            Id
            IdExpresion
          	Expresion {
              IdExpresion
              Expresion
            }
            IdOperador
          	Operador {
              Id
              Operador
            }
            IdExpresionC
            ExpresionC {
              IdExpresion
              Expresion
            }
            Centro
            Complejo
            Con
        }
        error
    }
}