query GetAllComprobarExpresiones {
    getAllComprobarExpresiones {
        Id
        IdExpresion
        Expresion {
          IdExpresion
          Expresion
        }
        IdOperador
        Operador {
          Id
          Operador
        }
        IdExpresionC
        ExpresionC {
          IdExpresion
          Expresion
        }
        Centro
        Complejo
        Con
        Centralizada
        IdDivision
    }
}