query GetComprobarExpresionById($id: Int!) {
    getComprobarExpresionById(id: $id) {
        success
        data {
            Id
            IdExpresion
            IdOperador
            IdExpresionC
            Centro
            Complejo
            Con
        }
        error
    }
}