query GetComprobarExpresionById($id: Int!) {
    getComprobarExpresionById(id: $id) {
        Id
        IdExpresion
        IdOperador
        IdExpresionC
        Centro
        Complejo
        Con
        Centralizada
        IdDivision
    }
}