mutation CreateComprobarExpresion($comprobarExpresionInput: ContaComprobarExpresionesInput!) {
    createComprobarExpresion(comprobarExpresionInput: $comprobarExpresionInput) {
        success
        error
    }
}