mutation SaveComprobarExpresion($comprobarExpresionInput: ContaComprobarExpresionesInput!) {
    saveComprobarExpresion(comprobarExpresionInput: $comprobarExpresionInput) {
        success
        error
    }
}