mutation UpdateComprobarExpresion($comprobarExpresionInput: ContaComprobarExpresionesInput!) {
    updateComprobarExpresion(comprobarExpresionInput: $comprobarExpresionInput) {
        success
        error
    }
}