query ConciliaDWH($conciliaDWHInput: ConciliaDWHInput!) {
    conciliaDWH(conciliaDWHInput: $conciliaDWHInput) {
        success
        data {
            Tipo
            IdCentro
            IdUnidad
            Unidad
            IdPiso
            Almacen
            Cuenta
            Periodo
            SaldoGolden
            SaldoRestaurador
            DifGoldenRest
            SaldoDistribuidor
            DifGoldenDist
            SaldoRodas
            DifGoldenRodas
            IdDivision
            Division
            CuentaR
            Nota
        }
        error
    }
}