query GetAllUnidades {
    getAllUnidades {
        success
        data {
            IdUnidad
            Nombre
            IdSubdivision
            Subdivision
            IdDivision
            Division
        }
        error
    }
}