query GetUnidadesByIdSubdivision($idSubdivision: Int!) {
    getUnidadesByIdSubdivision(idSubdivision: $idSubdivision) {
        success
        data {
            IdUnidad
            Nombre
            IdSubdivision
            IdDivision
        }
        error
    }
}