query GetUnidadesByIdDivision($idDivision: Int!) {
    getUnidadesByIdDivision(idDivision: $idDivision) {
        success
        data {
            IdUnidad
            Nombre
            IdSubdivision
            IdDivision
        }
        error
    }
}