query GetUnidadesByIdSubdivision($idSubdivision: Int!) {
    getUnidadesByIdSubdivision(idSubdivision: $idSubdivision) {
        IdUnidad
        Nombre
        IdSubdivision
        IdDivision
    }
}