query GetAllContaConexiones {
    getAllContaConexiones {
        Id
        IdUnidad
        Unidad {
            IdUnidad
            Nombre
            Division
        }
        IdDivision
        Consolidado
        IpRodas
        BaseDatos
    }
}