query GetAllContaConexiones {
    getAllContaConexiones {
        success
        data {
            Id
            IdUnidad
            Unidad {
              IdUnidad
              Nombre
              Division
            }
            IdDivision
            Consolidado
            IpRodas
            BaseDatos
        }
        error
    }
}