query GetAllContaConexiones {
    getAllContaConexiones {
        success
        data {
            Id
            IdUnidad
            Unidad {
                IdUnidad
                Nombre
            }
            IdDivision
            Division {
                IdDivision
                Division
            }
            Consolidado
            IpRodas
            Usuario
            BaseDatos
        }
        error
    }
}