query GetContaConexionById($id: Int!) {
    getContaConexionById(id: $id) {
        success
        data {
            Id
            IdUnidad
            Consolidado
            IdDivision
            IpRodas
            Usuario
            Contrasena
            BaseDatos
        }
        error
    }
}