query GetContaConexionesByDivision($idDivision: Int!) {
    getContaConexionesByDivision(idDivision: $idDivision) {
        success
        data {
            Id
            IdUnidad
            Unidad
            IdDivision
            Division
            Consolidado
            IpRodas
            Usuario
            BaseDatos
        }
        error
    }
}