query GetComprobarValorById($id: Int!) {
    getComprobarValorById(id: $id) {
      success
      data {
        Id
        IdCentro
        IdExpresion
        IdOperador
        Valor
        IdDivision
      }
      error
    }
}