query GetComprobarValorById($id: Int!) {
    getComprobarValorById(id: $id) {
        Id
        IdCentro
        IdExpresion
        IdOperador
        Valor
        IdDivision
        Consolidado
        Activo
    }
}