query GetDWHConexion($idDivision: Int!) {
    getDWHConexion(idDivision: $idDivision) {
        success
        data {
          IdUnidad
          ConexionRest
          ConexionDWH
        }
        error
    }
}