query ConciliaInternaDWH($conciliaInternaDWHInput: ConciliaOperacionesDWHInput!) {
  conciliaInternaDWH(conciliaInternaDWHInput: $conciliaInternaDWHInput) {
    success
    data {
      Documento
      FechaE
      FechaR
      Emisor
      Receptor
      ImporteE
      ImporteR
      Diferencia
    }
    error
  }
}