query ParteAtrasos($idDivision: Int!) {
  parteAtrasos(idDivision: $idDivision) {
    IdUnidad
    Unidad
    IdDivision
    Division
    AtrasoRest
    AtrasoDWH
    AtrasoDist
    AtrasoEmp
  }
  datosIdGAM(idDivision: $idDivision) {
    IdUnidad
    Unidad
    Ano
    Mes
    Fecha
    Version
    UltimaCircular
    PeriodoRestaurado
    vUtilnet
  }
}
