mutation SaveActFijosClasificadorSubgrupo($actFijosClasificadorSubgrupoInput: ActFijosClasificadorSubgrupoInput!) {
		saveActFijosClasificadorSubgrupo(actFijosClasificadorSubgrupoInput: $actFijosClasificadorSubgrupoInput) {
				Grupo
				Codigo
				Descripcion
				Tasa
		}
}