mutation SaveActFijosClasificadorCnmb($actfijosClasificadorCnmbInput: ActFijosClasificadorCnmbInput!) {
	saveActFijosClasificadorCnmb(actfijosClasificadorCnmbInput: $actfijosClasificadorCnmbInput) {
		CNMB
		DCNMB
		TREPO
	}
}