query GetAllSupervisores {
    getAllSupervisores {
        success
        data {
            IdSupervisor
            Supervisor
            Cargo {
                IdCargo
                Cargo
            }
            Division {
                IdDivision
                Division
            }
        }
        error
    }
}