query GetSupervisoresByIdDivision($idDivision: Int!) {
    getSupervisoresByIdDivision(idDivision: $idDivision) {
        success
        data {
            IdSupervisor
            Supervisor
            Cargo {
                IdCargo
                Cargo
            }
            Division {
                IdDivision
                Division
            }
        }
        error
    }
}