query GetAllExpresionesResumen {
    getAllExpresionesResumen {
        success
        data {
            IdExpresion
            Expresion
            Descripcion
            Acumulado
            OperacionesInternas
            Centralizada
        }
        error
    }
}