query GetExpresionResumenById($id: Int!) {
    getExpresionResumenById(id: $id) {
        success
        data {
            IdExpresion
            Expresion
            Descripcion
            Acumulado
            OperacionesInternas
            Centralizada
            IdDivision
        }
        error
    }
}