query GetExpresionesDetalleByIdResumen($idResumen: Int!) {
    getExpresionesDetalleByIdResumen(idResumen: $idResumen) {
        Id
        IdExpresion
        Cta
        SubCta
        Crit1
        Crit2
        Crit3
        Signo
        PorCiento
        TipoValor       
        TipoValorDesc     
    }
}