query GetExpresionResumenById($id: Int!) {
    getExpresionResumenById(id: $id) {
        IdExpresion
        Expresion
        Descripcion
        Acumulado
        OperacionesInternas
        Centralizada
        IdDivision
    }
}