query GetAllElementosGastos {
    getAllElementosGastos {
        success
        data {
            Egasto
            Descripcion
            UsoContenido
            TipoEntidad
            CuentaAsociada
            IdEpigrafe
        }
        error
    }
}