  query ContaEstadisticaParte {
    contaEstadisticaParte {
      IdDivision
      Division
      IdCentro
      Centro
      Consolidado
      Anno
      Periodo
      FechaActualizacion
      FechaInicio
      FechaFin
      Comprobantes
      Traspasados
      SinTraspasar
      Inconclusos
      Anulados
      Conexion
    }
  }