query GetAllClasificadorEntidades {
    getAllClasificadorEntidades {
        success
        data {
            IdUnidad
            Unidad
            IdTipoEntidad
            TipoEntidad
        }
        error
    }
}