query GetClasificadorEntidad($idUnidad: Int!) {
    getClasificadorEntidad(idUnidad: $idUnidad) {
        success
        data {
            IdUnidad
            IdTipoEntidad
        }
        error
    }
}