mutation CreateClasificadorEntidad($clasificadorEntidadInfo: ClasificadorEntidadInput!) {
    createClasificadorEntidad(clasificadorEntidadInfo: $clasificadorEntidadInfo) {
        success
        error
    }
}