mutation SaveClasificadorEntidad($clasificadorEntidadInfo: ClasificadorEntidadInput!) {
    saveClasificadorEntidad(clasificadorEntidadInfo: $clasificadorEntidadInfo) {
        success
        error
    }
}