mutation UpdateClasificadorEntidad($clasificadorEntidadInfo: ClasificadorEntidadInput!) {
    updateClasificadorEntidad(clasificadorEntidadInfo: $clasificadorEntidadInfo) {
        success
        error
    }
}