query AuthenticateUsuario($usuario: String!, $passw: String!) {
   authenticateUsuario(usuario: $usuario, passw: $passw) {
    success
    data {
      IdUsuario
      Usuario
      CambiarContrasena
      IdTipoUsuario
      IdDivision
      Token
    }
    error
  }
}