query AuthenticateUsuario($usuario: String!, $passw: String!) {
  authenticateUsuario(usuario: $usuario, passw: $passw) {
    IdUsuario
    Usuario
    CambiarContrasena
    IdTipoUsuario
    IdDivision
    Token
    RefreshToken
  }
}