query GetUsuariosByDivision($idDivision: Int!) {
   getUsuariosByDivision(idDivision: $idDivision) {
    success
    data {
      IdUsuario
      Usuario
      TipoUsuario {
        IdTipo
        TipoUsuario
      }
      Division {
        IdDivision
        Division
      }
    }
    error
  }
}