query GetNoUsarEnCuentaById($id: Int!) {
    getNoUsarEnCuentaById(id: $id) {
        success
        data {
            Id
            Codigo
            Cta
            SubCta
            Crit1
            Crit2
            Crit3
            Crit4
            Crit5
            Centralizada
            IdDivision
        }
        error
    }
}