mutation UpdateConciliacionEntreUnidades($conciliacionUnidadesInput: ConciliacionEntreUnidadesInput!) {
   updateConciliacionEntreUnidades(conciliacionUnidadesInput: $conciliacionUnidadesInput) {
    success
    error
  }
}