query ConciliaInternaConta($conciliaInternaContaInput: ConciliaInternaContaInput!) {
  conciliaInternaConta(conciliaInternaContaInput: $conciliaInternaContaInput) {
   	Division
    Annio
    Periodo
    Tipo
    Emisor
    Receptor
    CuentaE
    SubCuentaE
    ValorE
    Operador
    CuentaR
    SubCuentaR
    ValorR
    Diferencia
  }
}